secrets:
    db_password:
        file: ../secrets/db_password.txt
    db_root_password:
        file: ../secrets/db_root_password.txt
    wp_password:
        file: ../secrets/wp_password.txt

networks:
    BNet:
        name: BNet
        driver: bridge

volumes:
    mariadb_data:
        driver: local
        name: $DATABASE_VOL
        driver_opts:
            type: none
            o: bind
            device: /home/bn-bn/data/db
    wordpress_data:
        driver: local
        name: $WORDPRESS_VOL
        driver_opts:
            type: none
            o: bind
            device: /home/bn-bn/data/wordpress

services:

    # mandatory services

    nginx:
        container_name: nginx
        depends_on:
            - wordpress
        build: 
            context : requirements/nginx
            dockerfile: Dockerfile
        image: nginx:v1
        ports:
            - 443:443
        env_file:
            - .env
        networks:
            - BNet
        volumes:
            - wordpress_data:/var/www/wordpress
        restart: on-failure

    wordpress:
        container_name: wordpress
        depends_on:
            - mariadb
        build: 
            context : requirements/wordpress
            dockerfile: Dockerfile
        image: wordpress:v1
        env_file:
            - .env
        secrets:
            - db_password
            - wp_password
        networks:
            - BNet
        volumes:
            - wordpress_data:/var/www/wordpress
        restart: on-failure

    mariadb:
        container_name: mariadb
        build: 
            context : requirements/mariadb
            dockerfile: Dockerfile
        image: mariadb:v1
        env_file:
            - .env
        secrets:
            - db_password
            - db_root_password
        networks:
            - BNet
        volumes:
            - mariadb_data:/var/lib/mysql
        restart: on-failure

    # bonus services

    redis:
        container_name: redis
        image: redis:v1
        build:
            context: requirements/bonus/redis
            dockerfile: Dockerfile
        networks:
            - BNet
        restart: on-failure
    
    adminer:
        container_name: adminer
        depends_on:
            - mariadb
        image: adminer:v1
        build:
            context: requirements/bonus/adminer
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        networks:
            - BNet
        restart: on-failure

    website:
        container_name: website
        image: site:v1
        build:
            context: requirements/bonus/static
            dockerfile: Dockerfile
        ports:
            - 81:80
        networks:
            - BNet
        restart: on-failure

    monitorix:
        container_name: monitorix
        image: monitorix:v1
        build:
            context: requirements/bonus/monitorix
            dockerfile: Dockerfile
        networks:
            - BNet
        ports:
            - 82:8080
        restart: on-failure
