secrets:
    db_password:
        file: ../secrets/db_password.txt
    db_root_password:
        file: ../secrets/db_root_password.txt
    wp_password:
        file: ../secrets/wp_password.txt
    ftp_password:
        file: ../secrets/ftp_password.txt

networks:
    BNet:
        driver: bridge

volumes:
    mariadb_vol:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/bn-bn/data/db
    wordpress_vol:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/bn-bn/data/wordpress

services:

    # mandatory services

    nginx:
        container_name: nginx
        depends_on:
            - wordpress
        build: requirements/nginx
        image: nginx
        ports:
            - 443:443
        env_file:
            - .env
        networks:
            - BNet
        volumes:
            - wordpress_vol:/var/www/wordpress
        restart: on-failure

    wordpress:
        container_name: wordpress
        depends_on:
            - mariadb
        build: requirements/wordpress
        image: wordpress
        env_file:
            - .env
        secrets:
            - db_password
            - wp_password
        networks:
            - BNet
        volumes:
            - wordpress_vol:/var/www/wordpress
        restart: on-failure

    mariadb:
        container_name: mariadb
        build: requirements/mariadb
        image: mariadb
        env_file:
            - .env
        secrets:
            - db_password
            - db_root_password
        networks:
            - BNet
        volumes:
            - mariadb_vol:/var/lib/mysql
        restart: on-failure

    # bonus services

    redis:
        container_name: redis
        image: redis
        build: requirements/bonus/redis
        networks:
            - BNet
        restart: on-failure
    
    adminer:
        container_name: adminer
        depends_on:
            - mariadb
        image: adminer
        build: requirements/bonus/adminer
        ports:
            - 8080:8080
        networks:
            - BNet
        restart: on-failure

    website:
        container_name: website
        image: site
        build: requirements/bonus/static
        ports:
            - 81:80
        networks:
            - BNet
        restart: on-failure

    file-browser:
        container_name: file-browser
        build: requirements/bonus/file-browser
        image: file-browser
        restart: on-failure
        volumes:
            - wordpress_vol:/data/wordpress
            - mariadb_vol:/data/mariadb
        networks:
            - BNet
        ports:
            - "3201:8080"
    ftp:
        container_name: ftp
        image: ftp
        build: requirements/bonus/ftp
        networks:
            - BNet
        ports:
            - 21:21
            - 40000-40005:40000-40005
        volumes:
            - wordpress_vol:/var/www/wordpress
        secrets:
            - ftp_password
        env_file:
            - .env
        restart: on-failure
