server {
    listen 443 ssl;
    server_name kben-tou.42.fr;

    ssl_certificate     /etc/nginx/ssl/certs/bn.crt;
    ssl_certificate_key /etc/nginx/ssl/private/bn.key;

    ssl_protocols       TLSv1.2 TLSv1.3;

    root /var/www/wordpress;
    index index.php;

    location ~ \.php {
        include fastcgi_params;
        fastcgi_pass wordpress:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location /adminer {
        proxy_pass http://adminer:8080;
    }

    location /static/ {
        proxy_pass http://website:80/;
    }

    location /cadvisor/ {
        proxy_pass http://cadvisor:8080;
    }
}