listen=YES
listen_ipv6=NO

local_enable=YES
write_enable=YES

chroot_local_user=YES
allow_writeable_chroot=YES
seccomp_sandbox=NO

local_root=/var/www/wordpress

pasv_enable=YES
pasv_min_port=40000
pasv_max_port=40005
pasv_address=0.0.0.0